# CLI config: https://github.com/DavidAnson/markdownlint-cli2?tab=readme-ov-file#markdownlint-cli2jsonc
# Lint rules: https://github.com/DavidAnson/markdownlint?tab=readme-ov-file#rules--aliases

config:
  line-length:
    line_length: 120
  no-inline-html:
    allowed_elements:
      - dl
      - dt
      - dd
      - details
      - summary
      - code
  ul-style:
    style: dash

globs:
  - '**/*.md'
  - '!node_modules'
  - '!vendor'

gitignore: true
showFound: true
