volumes:
  vscode-extensions:

services:
  php:
    user: ${FIXUID:-1000}:${FIXGID:-1000}
    command: ["sh", "-c", "trap : 15 ; sleep 9999d & wait"]
    entrypoint: ["fixuid", "-q"]
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        IMAGE_REGISTRY_PHP: $IMAGE_REGISTRY_PHP
        IMAGE_TAG_PHP: $IMAGE_TAG_PHP
    volumes:
      - $HOME/.ssh/known_hosts:/home/code/.ssh/known_hosts:ro
      # - $HOME/.composer/auth.json:/home/code/.composer/auth.json:ro
      - .:/workspace:delegated
      - vscode-extensions:/home/code/.vscode-server/extensions
      - ./.devcontainer/050-xdebug.ini:/usr/local/etc/php/conf.d/050-xdebug.ini
