name: Setup PHP

inputs:
  coverage:
    description: Set PHP coverage driver
    type: string
    default: "none"

runs:
  using: composite
  steps:
    - name: Get composer cache directory
      id: composer-cache-dir
      shell: bash
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Restore Composer cache
      id: composer-cache
      uses: actions/cache/restore@v4.0.2
      with:
        path: |
          ${{ steps.composer-cache-dir.outputs.dir }}
          vendor
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}

    - name: Setup PHP
      uses: shivammathur/setup-php@2.30.2
      with:
        php-version: "8.3"
        coverage: ${{ inputs.coverage }}

    - name: Install dependencies
      shell: bash
      run: composer install
